import _add from './add.svg';
import _advance from './advance.svg';
import _arroba from './arroba.svg';
import _bars from './bars.svg';
import _bagMoneyBlack from './bag-money-black.svg';
import _bagMoney from './bag-money.svg';
import _bagWhiteLineBlue from './bag-white-line-blue.svg';
import _bag from './bag.svg';
import _bellAdd from './bell-add.svg';
import _bellBlock from './bell-block.svg';
import _bell from './bell.svg';
import _block from './block.svg';
import _board from './board.svg';
import _box from './box.svg';
import _btnLess from './btn-less.svg';
import _btnMore from './btn-more.svg';
import _cache from './cache.svg';
import _cadeado from './cadeado.svg';
// export {default as calendar-add} from './calendar-add.svg';
// export {default as calendar} from './calendar.svg';
// export {default as cart} from './cart.svg';
// export {default as cellphone} from './cellphone.svg';
// export {default as chart-area} from './chart-area.svg';
// export {default as chart-bars} from './chart-bars.svg';
// export {default as chart-board} from './chart-board.svg';
// export {default as chart-camera} from './chart-camera.svg';
// export {default as chart-candles} from './chart-candles.svg';
// export {default as chart-compare} from './chart-compare.svg';
// export {default as chart-function} from './chart-function.svg';
// export {default as chart-line} from './chart-line.svg';
// export {default as chart-line_1} from './chart-line_1.svg';
// export {default as chart-save} from './chart-save.svg';
// export {default as chart-undo} from './chart-undo.svg';
// export {default as chat-do} from './chat-do.svg';
// export {default as chat} from './chat.svg';
// export {default as checkmark-selected} from './checkmark-selected.svg';
// export {default as checkmark} from './checkmark.svg';
// export {default as circle-down} from './circle-down.svg';
// export {default as circle-more} from './circle-more.svg';
// export {default as clipboard-chart} from './clipboard-chart.svg';
// export {default as clips} from './clips.svg';
// export {default as clock} from './clock.svg';
// export {default as close} from './close.svg';
// export {default as comment-star} from './comment-star.svg';
// export {default as comment} from './comment.svg';
// export {default as comments} from './comments.svg';
// export {default as compass} from './compass.svg';
// export {default as config} from './config.svg';
// export {default as console} from './console.svg';
// export {default as coupom} from './coupom.svg';
// export {default as diamond-blue-dark} from './diamond-blue-dark.svg';
// export {default as diamond-blue-grey} from './diamond-blue-grey.svg';
// export {default as diamond-blue-white} from './diamond-blue-white.svg';
// export {default as diamond-solid-dark} from './diamond-solid-dark.svg';
// export {default as down} from './down.svg';
// export {default as draw-arrow} from './draw-arrow.svg';
// export {default as draw-circle} from './draw-circle.svg';
// export {default as draw-fibonacci-arc} from './draw-fibonacci-arc.svg';
// export {default as draw-fibonacci-fan} from './draw-fibonacci-fan.svg';
// export {default as draw-fibonacci-retracement} from './draw-fibonacci-retracement.svg';
// export {default as draw-fibonacci-timezone} from './draw-fibonacci-timezone.svg';
// export {default as draw-horizontal-arrow} from './draw-horizontal-arrow.svg';
// export {default as draw-horizontal-line} from './draw-horizontal-line.svg';
// export {default as draw-horizontal-range} from './draw-horizontal-range.svg';
// export {default as draw-horizontal-ray} from './draw-horizontal-ray.svg';
// export {default as draw-infinity} from './draw-infinity.svg';
// export {default as draw-pitchfork} from './draw-pitchfork.svg';
// export {default as draw-ray} from './draw-ray.svg';
// export {default as draw-retangle} from './draw-retangle.svg';
// export {default as draw-text} from './draw-text.svg';
// export {default as draw-trend-channel} from './draw-trend-channel.svg';
// export {default as draw-trend-line} from './draw-trend-line.svg';
// export {default as draw-triangle} from './draw-triangle.svg';
// export {default as draw-vertical-line} from './draw-vertical-line.svg';
// export {default as draw-vertical-range} from './draw-vertical-range.svg';
// export {default as emoji-airplane} from './emoji-airplane.svg';
// export {default as emoji-ball} from './emoji-ball.svg';
// export {default as emoji-clock} from './emoji-clock.svg';
// export {default as emoji-face} from './emoji-face.svg';
// export {default as emoji-flag} from './emoji-flag.svg';
// export {default as emoji-folha} from './emoji-folha.svg';
// export {default as emoji-hamburger} from './emoji-hamburger.svg';
// export {default as emoji-hearth} from './emoji-hearth.svg';
// export {default as emoji-lamp} from './emoji-lamp.svg';
// export {default as emoticon-add} from './emoticon-add.svg';
// export {default as external-link} from './external-link.svg';
// export {default as file-people} from './file-people.svg';
// export {default as folder} from './folder.svg';
// export {default as funnel} from './funnel.svg';
// export {default as grid} from './grid.svg';
// export {default as hammer-blue-gray} from './hammer-blue-gray.svg';
// export {default as hammer-blue-white} from './hammer-blue-white.svg';
// export {default as hammer-white-blue} from './hammer-white-blue.svg';
// export {default as hand} from './hand.svg';
// export {default as headphone} from './headphone.svg';
// export {default as heart} from './heart.svg';
// export {default as home} from './home.svg';
// export {default as ic-central-ajuda} from './ic-central-ajuda.svg';
// export {default as ic-pause} from './ic-pause.svg';
// export {default as ic-play} from './ic-play.svg';
// export {default as ico-carteira} from './ico-carteira.svg';
// export {default as image} from './image.svg';
// export {default as lamp} from './lamp.svg';
// export {default as left} from './left.svg';
// export {default as link} from './link.svg';
// export {default as list} from './list.svg';
// export {default as marker} from './marker.svg';
// export {default as menu} from './menu.svg';
// export {default as microphone} from './microphone.svg';
// export {default as moderador-blue-dark} from './moderador-blue-dark.svg';
// export {default as moderador-blue-grey} from './moderador-blue-grey.svg';
// export {default as moderador-blue-white} from './moderador-blue-white.svg';
// export {default as moderador-blue} from './moderador-blue.svg';
// export {default as moderador-solid-dark} from './moderador-solid-dark.svg';
// export {default as money-circle} from './money-circle.svg';
// export {default as money} from './money.svg';
// export {default as more-options} from './more-options.svg';
// export {default as ok} from './ok.svg';
// export {default as paper-plane} from './paper-plane.svg';
// export {default as parcerias} from './parcerias.svg';
// export {default as photo} from './photo.svg';
// export {default as plantao} from './plantao.svg';
// export {default as play} from './play.svg';
// export {default as player-block} from './player-block.svg';
// export {default as player} from './player.svg';
// export {default as radar} from './radar.svg';
// export {default as reload} from './reload.svg';
// export {default as right} from './right.svg';
// export {default as search} from './search.svg';
// export {default as set-down} from './set-down.svg';
// export {default as share} from './share.svg';
// export {default as sign-out} from './sign-out.svg';
// export {default as small-important} from './small-important.svg';
// export {default as small-sound} from './small-sound.svg';
// export {default as social-facebook} from './social-facebook.svg';
// export {default as social-set} from './social-set.svg';
// export {default as social-twitter} from './social-twitter.svg';
// export {default as social-whatsapp} from './social-whatsapp.svg';
// export {default as social-youtube} from './social-youtube.svg';
// export {default as sort-amount-down} from './sort-amount-down.svg';
// export {default as star-bkgd-white} from './star-bkgd-white.svg';
// export {default as star-solid-dark} from './star-solid-dark.svg';
// export {default as star-white} from './star-white.svg';
// export {default as star-yellow-blue} from './star-yellow-blue.svg';
// export {default as star-yellow-grey} from './star-yellow-grey.svg';
// export {default as star-yellow-white} from './star-yellow-white.svg';
// export {default as star} from './star.svg';
// export {default as tc-blue-dark} from './tc-blue-dark.svg';
// export {default as tc-blue-grey} from './tc-blue-grey.svg';
// export {default as tc-blue-white} from './tc-blue-white.svg';
// export {default as tc-icons-arrow} from './tc-icons-arrow.svg';
// export {default as tc-icons-back} from './tc-icons-back.svg';
// export {default as tc-icons-blog} from './tc-icons-blog.svg';
// export {default as tc-icons-calculator} from './tc-icons-calculator.svg';
// export {default as tc-icons-calendar} from './tc-icons-calendar.svg';
// export {default as tc-icons-check} from './tc-icons-check.svg';
// export {default as tc-icons-clessidre} from './tc-icons-clessidre.svg';
// export {default as tc-icons-close} from './tc-icons-close.svg';
// export {default as tc-icons-comment} from './tc-icons-comment.svg';
// export {default as tc-icons-company} from './tc-icons-company.svg';
// export {default as tc-icons-compare-proposals} from './tc-icons-compare-proposals.svg';
// export {default as tc-icons-document} from './tc-icons-document.svg';
// export {default as tc-icons-download} from './tc-icons-download.svg';
// export {default as tc-icons-edit} from './tc-icons-edit.svg';
// export {default as tc-icons-equity} from './tc-icons-equity.svg';
// export {default as tc-icons-estate} from './tc-icons-estate.svg';
// export {default as tc-icons-filters} from './tc-icons-filters.svg';
// export {default as tc-icons-financing} from './tc-icons-financing.svg';
// export {default as tc-icons-hide} from './tc-icons-hide.svg';
// export {default as tc-icons-home} from './tc-icons-home.svg';
// export {default as tc-icons-lock} from './tc-icons-lock.svg';
// export {default as tc-icons-locked} from './tc-icons-locked.svg';
// export {default as tc-icons-log-out} from './tc-icons-log-out.svg';
// export {default as tc-icons-maximize} from './tc-icons-maximize.svg';
// export {default as tc-icons-menu} from './tc-icons-menu.svg';
// export {default as tc-icons-more} from './tc-icons-more.svg';
// export {default as tc-icons-no-events} from './tc-icons-no-events.svg';
// export {default as tc-icons-notification} from './tc-icons-notification.svg';
// export {default as tc-icons-pen} from './tc-icons-pen.svg';
// export {default as tc-icons-plus} from './tc-icons-plus.svg';
// export {default as tc-icons-proposal-details} from './tc-icons-proposal-details.svg';
// export {default as tc-icons-revert} from './tc-icons-revert.svg';
// export {default as tc-icons-search} from './tc-icons-search.svg';
// export {default as tc-icons-settings} from './tc-icons-settings.svg';
// export {default as tc-icons-share} from './tc-icons-share.svg';
// export {default as tc-icons-show} from './tc-icons-show.svg';
// export {default as tc-icons-tools} from './tc-icons-tools.svg';
// export {default as tc-icons-trade-ideas} from './tc-icons-trade-ideas.svg';
// export {default as tc-icons-trash} from './tc-icons-trash.svg';
// export {default as tc-icons-user} from './tc-icons-user.svg';
// export {default as tc-icons-wealth} from './tc-icons-wealth.svg';
// export {default as tc-matrix} from './tc-matrix.svg';
// export {default as tc-small-arrow} from './tc-small-arrow.svg';
// export {default as tc-small-back} from './tc-small-back.svg';
// export {default as tc-small-check} from './tc-small-check.svg';
// export {default as tc-small-clessidre} from './tc-small-clessidre.svg';
// export {default as tc-small-clock} from './tc-small-clock.svg';
// export {default as tc-small-close} from './tc-small-close.svg';
// export {default as tc-small-comment} from './tc-small-comment.svg';
// export {default as tc-small-copy} from './tc-small-copy.svg';
// export {default as tc-small-document} from './tc-small-document.svg';
// export {default as tc-small-download} from './tc-small-download.svg';
// export {default as tc-small-info} from './tc-small-info.svg';
// export {default as tc-small-lock} from './tc-small-lock.svg';
// export {default as tc-small-plus} from './tc-small-plus.svg';
// export {default as tc-small-revert} from './tc-small-revert.svg';
// export {default as tc-small-settings} from './tc-small-settings.svg';
// export {default as tc-text-editor-attach} from './tc-text-editor-attach.svg';
// export {default as tc-text-editor-bold} from './tc-text-editor-bold.svg';
// export {default as tc-text-editor-center-align} from './tc-text-editor-center-align.svg';
// export {default as tc-text-editor-image} from './tc-text-editor-image.svg';
// export {default as tc-text-editor-indent-left} from './tc-text-editor-indent-left.svg';
// export {default as tc-text-editor-indent-right} from './tc-text-editor-indent-right.svg';
// export {default as tc-text-editor-italic} from './tc-text-editor-italic.svg';
// export {default as tc-text-editor-left-align} from './tc-text-editor-left-align.svg';
// export {default as tc-text-editor-link} from './tc-text-editor-link.svg';
// export {default as tc-text-editor-list-01} from './tc-text-editor-list-01.svg';
// export {default as tc-text-editor-list-02} from './tc-text-editor-list-02.svg';
// export {default as tc-text-editor-quote} from './tc-text-editor-quote.svg';
// export {default as tc-text-editor-right-align} from './tc-text-editor-right-align.svg';
// export {default as tc-text-editor-strikethrough} from './tc-text-editor-strikethrough.svg';
// export {default as tc-text-editor-underline} from './tc-text-editor-underline.svg';
// export {default as tcnews} from './tcnews.svg';
// export {default as termina-tcschool} from './termina-tcschool.svg';
// export {default as terminal-cotacoes} from './terminal-cotacoes.svg';
// export {default as terminal-cursos} from './terminal-cursos.svg';
// export {default as terminal-eventos} from './terminal-eventos.svg';
// export {default as terminal-loja} from './terminal-loja.svg';
// export {default as terminal-master} from './terminal-master.svg';
// export {default as terminal-plantao} from './terminal-plantao.svg';
// export {default as terminal-podcasts} from './terminal-podcasts.svg';
// export {default as terminal-relatorio} from './terminal-relatorio.svg';
// export {default as terminal-trad3} from './terminal-trad3.svg';
// export {default as terminal-trade-ideas} from './terminal-trade-ideas.svg';
// export {default as terminal-videos} from './terminal-videos.svg';
// export {default as terminal} from './terminal.svg';
// export {default as trad3} from './trad3.svg';
// export {default as trash} from './trash.svg';
// export {default as trophy} from './trophy.svg';
// export {default as up} from './up.svg';
// export {default as user-add} from './user-add.svg';
// export {default as zoom-out} from './zoom-out.svg';
// export {default as zoom} from './zoom.svg';
export const add = _add;
export const cadeado = _cadeado;
export const advance = _advance;
export const cache = _cache;
export const arroba = _arroba;
export const btnMore = _btnMore;
export const bars = _bars;
export const btnLess = _btnLess;
export const bagMoneyBlack = _bagMoneyBlack;
export const box = _box;
export const bagMoney = _bagMoney;
export const board = _board;
export const bagWhiteLineBlue = _bagWhiteLineBlue;
export const block = _block;
export const bag = _bag;
export const bell = _bell;
export const bellAdd = _bellAdd;
export const bellBlock = _bellBlock;
//# sourceMappingURL=index.js.map