/// <reference types="react" />
export declare const Add: import("react").FC<TCSvgProps>;
export declare const Cadeado: import("react").FC<TCSvgProps>;
export declare const Advance: import("react").FC<TCSvgProps>;
export declare const Cache: import("react").FC<TCSvgProps>;
export declare const Arroba: import("react").FC<TCSvgProps>;
export declare const BtnMore: import("react").FC<TCSvgProps>;
export declare const Bars: import("react").FC<TCSvgProps>;
export declare const BtnLess: import("react").FC<TCSvgProps>;
export declare const BagMoneyBlack: import("react").FC<TCSvgProps>;
export declare const Box: import("react").FC<TCSvgProps>;
export declare const BagMoney: import("react").FC<TCSvgProps>;
export declare const Board: import("react").FC<TCSvgProps>;
export declare const BagWhiteLineBlue: import("react").FC<TCSvgProps>;
export declare const Block: import("react").FC<TCSvgProps>;
export declare const Bag: import("react").FC<TCSvgProps>;
export declare const Bell: import("react").FC<TCSvgProps>;
export declare const BellAdd: import("react").FC<TCSvgProps>;
export declare const BellBlock: import("react").FC<TCSvgProps>;
