/// <reference types="react" />
export declare const add: import("react").FC<TCSvgProps>;
export declare const cadeado: import("react").FC<TCSvgProps>;
export declare const advance: import("react").FC<TCSvgProps>;
export declare const cache: import("react").FC<TCSvgProps>;
export declare const arroba: import("react").FC<TCSvgProps>;
export declare const btnMore: import("react").FC<TCSvgProps>;
export declare const bars: import("react").FC<TCSvgProps>;
export declare const btnLess: import("react").FC<TCSvgProps>;
export declare const bagMoneyBlack: import("react").FC<TCSvgProps>;
export declare const box: import("react").FC<TCSvgProps>;
export declare const bagMoney: import("react").FC<TCSvgProps>;
export declare const board: import("react").FC<TCSvgProps>;
export declare const bagWhiteLineBlue: import("react").FC<TCSvgProps>;
export declare const block: import("react").FC<TCSvgProps>;
export declare const bag: import("react").FC<TCSvgProps>;
export declare const bell: import("react").FC<TCSvgProps>;
export declare const bellAdd: import("react").FC<TCSvgProps>;
export declare const bellBlock: import("react").FC<TCSvgProps>;
